# Generated by Django 4.2.7 on 2023-11-21 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Practica18', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='fecha_nacimiento',
        ),
    ]
